# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Define another job
  get_name:
    runs-on: ubuntu-latest
    outputs:
      my_name: ${{ steps.step1.outputs.name }}
    steps:
      - id: step1
        run: echo "name=Steven" >> "$GITHUB_OUTPUT"
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run with output from another job
        run: echo "Hello $OUTPUT1"
        env:
          OUTPUT1: ${{jobs.get_name.outputs.my_name}}
