# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Define another job
  get_name:
    runs-on: ubuntu-latest
    outputs:
      my_name: ${{ steps.step1.outputs.name }}
      my_version: ${{ steps.step2.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      
      - id: step1
        run: echo "name=Steven" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "version=$(pwsh -command '[xml]$pom=get-content ./pom.xml;$pom.project.version')" >> "$GITHUB_OUTPUT"
      
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: get_name

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Run with output from another job
        run: echo "Hello $OUTPUT1, your version is $OUTPUT2"
        env:
          OUTPUT1: ${{needs.get_name.outputs.my_name}}
          OUTPUT2: ${{needs.get_name.outputs.my_version}}
