# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Define another job
  get_name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - id: step1
        run: echo "name=Steven" >> "$GITHUB_ENV"
      - id: step2
        run: echo "version=$(pwsh -command '[xml]$pom=get-content ./pom.xml;$pom.project.version')" >> "$GITHUB_ENV"

      - name: Run with output from another job
        run: echo "Hello $name, your version is $version"
